---
deployment:
  tasks:
    - export DEPLOYHOMESPATH=/home/sitejsvh/treyjcausey.com
    - /bin/cp index.php $DEPLOYHOMESPATH
    //- /bin/cp composer.json $DEPLOYHOMESPATH
    //- /bin/cp composer.lock $DEPLOYHOMESPATH
    //- export DEPLOYVENDORSPATH=/home/sitejsvh/treyjcausey.com
    //- /bin/cp -r /vendor $DEPLOYVENDORSPATH